<?php
/**
 * @file
 * Drupal needs this blank file.
 */
/**
 * Implements hook_form_FORM_ID_alter().
 */
function stanford_wysiwyg_form_wysiwyg_profile_form_alter(&$form, &$form_state, $form_id) {
  $form['css']['css_path']['#maxlength'] = 1024;
  $form['css']['css_path']['#size'] = 120;
}

/**
 * Implements hook_wysiwyg_editor_settings_alter().
 */

function stanford_wysiwyg_editor_settings_alter(&$settings, $context) {
  // add editor CSS to fix overflow issue
  $editor_css = url(drupal_get_path('module', 'stanford_wysiwyg') . '/css/editor.css');
  $settings['contentsCss'][] = $editor_css;
  // find default theme; add CSS for stanford themes
  $theme_default = variable_get('theme_default');
  switch ($theme_default) {
    case 'open_framework' :
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'open_framework') . '/bootstrap/css/bootstrap.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'open_framework') . '/css/open_framework.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'stanford_framework') . '/css/stanford_framework.css');
      break;
    case 'stanford_basic' :
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'stanford_basic') . '/css/stanford_basic.css');
      break;
    case 'stanford_framework' :
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'open_framework') . '/bootstrap/css/bootstrap.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'open_framework') . '/css/open_framework.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'stanford_framework') . '/css/stanford_framework.css');
      break;
    case 'stanford_branner' :
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'open_framework') . '/bootstrap/css/bootstrap.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'open_framework') . '/css/open_framework.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'stanford_framework') . '/css/stanford_framework.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'stanford_branner') . '/css/stanford_branner.css');
      break;
    case 'stanford_jordan' :
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'open_framework') . '/bootstrap/css/bootstrap.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'open_framework') . '/css/open_framework.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'stanford_framework') . '/css/stanford_framework.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'stanford_jordan') . '/css/stanford_jordan.css');
      break;
    case 'stanford_wilbur' :
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'open_framework') . '/bootstrap/css/bootstrap.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'open_framework') . '/css/open_framework.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'stanford_framework') . '/css/stanford_framework.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'stanford_wilbur') . '/css/stanford_wilbur.css');
      break;
    case 'stanfordmodern' :
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'stanfordmodern') . '/css/stanfordmodern.css');
      break;
  }
}