<?php
/**
 * @file
 * Drupal needs this blank file.
 */
/**
 * Implements hook_form_FORM_ID_alter().
 */
function stanford_wysiwyg_form_wysiwyg_profile_form_alter(&$form, &$form_state, $form_id) {
  $form['css']['css_path']['#maxlength'] = 1024;
  $form['css']['css_path']['#size'] = 120;
}

/**
 * Implements hook_wysiwyg_editor_settings_alter().
 */

function stanford_wysiwyg_wysiwyg_editor_settings_alter(&$settings, $context) {
  // Add editor CSS to fix overflow issue.
  $editor_css = file_create_url(drupal_get_path('module', 'stanford_jumpstart_wysiwyg') . '/css/editor.css');
  $settings['contentsCss'][] = $editor_css;
  // Find default theme.
  $theme_default = variable_get('theme_default');
  // Add CSS for Stanford themes.
  stanford_wysiwyg_compute_css($theme_default, $settings);
}

function stanford_wysiwyg_compute_css($theme, &$settings) {
  // Find ALL THE THEMES.
  $themes = list_themes();
  // This setting requires built-in theme support, for variable CSS.
  $css = variable_get($theme . '_wysiwyg_css');
  // If it's a theme with variable CSS, like stanford_framework or stanford_light, use the CSS From the variable.
  if (isset($css)) {
    foreach ($css as $css_file) {
      $settings['contentsCss'][] = file_create_url($css_file);
    }
  }
  // If not, load the CSS from the .info file(s) of the theme and its base theme(s)
  else {
    // Get the CSS from the base theme(s).
    $base_themes = array_keys($themes[$theme]->base_themes);
    foreach ($base_themes as $base_theme) {
      foreach ($themes[$base_theme]->stylesheets['all'] as $css_file) {
        $settings['contentsCss'][] = file_create_url($css_file);
      }
    }
    foreach ($themes[$theme]->stylesheets['all'] as $css_file) {
      $settings['contentsCss'][] = file_create_url($css_file);
    }
  }
}